### ISSUE TITLE
Support other datastores besides mongodb

### ISSUE THREAD

**Issue by kadams54** [switchboardpy/switchboard#16]
If we want to support other backends, using https://pypi.python.org/pypi/datastore might be the best way to go.

**Comment by brondsem** [comment]
That package worked well for me on a little project called "gazette".  Here's some references of how it was used there:

Custom datastores, wrappers, serializers: https://sourceforge.net/p/gazette/code/ci/master/tree/api/python/gazette/utils.py

Usage: https://sourceforge.net/p/gazette/code/ci/master/tree/README.md near bottom
